Repository netwerk-digitaal-erfgoed/solid-crs, pull requests merged in 2021-12, with the labels that each got.

#526 feat: add paginator to collection page
  packages/solid-crs-components/lib/demo.ts
  packages/solid-crs-components/lib/index.ts
  packages/solid-crs-components/lib/paginator/paginator.component.spec.ts
  packages/solid-crs-components/lib/paginator/paginator.component.ts
  packages/solid-crs-components/package.json
  packages/solid-crs-components/tests/setup.ts
  packages/solid-crs-core/package.json
  packages/solid-crs-manage/lib/app.ts
  packages/solid-crs-manage/lib/features/collection/collection-root.component.spec.ts
  packages/solid-crs-manage/lib/features/collection/collection-root.component.ts
  packages/solid-crs-manage/lib/public/nl-NL.json
  packages/solid-crs-manage/package.json
  packages/solid-crs-pods/data/hetlageland/heritage-objects/data-1$.ttl
  packages/solid-crs-presentation/lib/app.ts
  packages/solid-crs-presentation/lib/features/collection/collection-root.component.ts
  packages/solid-crs-presentation/lib/public/nl-NL.json
  packages/solid-crs-presentation/package.json
Labels: enhancement

#528 fix: requirements for datasets violations
  packages/solid-crs-client/lib/index.ts
  packages/solid-crs-client/package-lock.json
  packages/solid-crs-client/package.json
  packages/solid-crs-core/lib/solid/collection-object-solid-store.spec.ts
  packages/solid-crs-core/lib/solid/collection-object-solid-store.ts
  packages/solid-crs-core/lib/solid/collection-solid-store.spec.ts
  packages/solid-crs-core/lib/solid/collection-solid-store.ts
  packages/solid-crs-core/lib/solid/solid-store.spec.ts
  packages/solid-crs-core/lib/solid/solid-store.ts
  packages/solid-crs-core/package.json
  packages/solid-crs-core/testresults
  packages/solid-crs-manage/lib/app-root.component.ts
  packages/solid-crs-manage/lib/app.machine.ts
  packages/solid-crs-manage/lib/features/collection/collection.machine.ts
  packages/solid-crs-manage/package-lock.json
  packages/solid-crs-presentation/package-lock.json
Labels: bug

#530 docs: update order of install instructions
  docs/modules/manual/pages/install.adoc
Labels: documentation

#531 chore: enable strict mode for components
  package.json
  packages/solid-crs-client/package-lock.json
  packages/solid-crs-client/package.json
  packages/solid-crs-components/lib/alerts/alert.component.spec.ts
  packages/solid-crs-components/lib/alerts/alert.component.ts
  packages/solid-crs-components/lib/alerts/popup.component.ts
  packages/solid-crs-components/lib/collections/card.component.ts
  packages/solid-crs-components/lib/collections/collection-card.component.spec.ts
  packages/solid-crs-components/lib/collections/collection-card.component.ts
  packages/solid-crs-components/lib/collections/large-card.component.ts
  packages/solid-crs-components/lib/collections/object-card.component.ts
  packages/solid-crs-components/lib/demo/demo-card.component.ts
  packages/solid-crs-components/lib/demo/demo-content-header.component.ts
  packages/solid-crs-components/lib/demo/demo-form.component.ts
  packages/solid-crs-components/lib/demo/demo-large-card.component.ts
  packages/solid-crs-components/lib/demo/demo-sidebar-list.component.ts
  packages/solid-crs-components/lib/demo/demo-svg.component.ts
  packages/solid-crs-components/lib/forms/form-element.component.spec.ts
  packages/solid-crs-components/lib/forms/form-element.component.ts
  packages/solid-crs-components/lib/forms/form.events.ts
  packages/solid-crs-components/lib/forms/form.machine.spec.ts
  packages/solid-crs-components/lib/forms/form.machine.ts
  packages/solid-crs-components/lib/header/content-header.component.ts
  packages/solid-crs-components/lib/loading/progress-bar-component.ts
  packages/solid-crs-components/lib/paginator/paginator.component.spec.ts
  packages/solid-crs-components/lib/paginator/paginator.component.ts
  packages/solid-crs-components/lib/sidebar/sidebar-item.component.ts
  packages/solid-crs-components/lib/sidebar/sidebar-list-item.component.ts
  packages/solid-crs-components/lib/sidebar/sidebar-list.component.ts
  packages/solid-crs-components/lib/sidebar/sidebar.component.ts
  packages/solid-crs-components/lib/state/schema.ts
  packages/solid-crs-components/package-lock.json
  packages/solid-crs-components/package.json
  packages/solid-crs-components/tsconfig.json
  packages/solid-crs-components/tsconfig.spec.json
  packages/solid-crs-core/package-lock.json
  packages/solid-crs-core/package.json
  packages/solid-crs-manage/lib/app-root.component.ts
  packages/solid-crs-manage/lib/features/collection/collection-root.component.ts
  packages/solid-crs-manage/package-lock.json
  packages/solid-crs-manage/package.json
  packages/solid-crs-presentation/lib/app-root.component.ts
  packages/solid-crs-presentation/package-lock.json
  packages/solid-crs-presentation/package.json
  packages/solid-crs-semcom-components/lib/object-creation.component.ts
  packages/solid-crs-semcom-components/lib/object-dimensions.component.ts
  packages/solid-crs-semcom-components/lib/object-identification.component.ts
  packages/solid-crs-semcom-components/lib/object-imagery.component.ts
  packages/solid-crs-semcom-components/lib/object-representation.component.ts
  packages/solid-crs-semcom-components/lib/object.component.spec.ts
  packages/solid-crs-semcom-components/package-lock.json
  packages/solid-crs-semcom-components/package.json
  packages/solid-crs-semcom-components/tsconfig.json
  packages/solid-crs-semcom-components/tsconfig.spec.json
Labels: manage-complexity

#537 chore: add build script to id-proxy
  packages/solid-crs-id-proxy/package-lock.json
  packages/solid-crs-id-proxy/package.json
Labels: bug

#538 feat: set up WebID server
  .github/workflows/ci.yml
  nde-erfgoed.code-workspace
  packages/solid-crs-id-proxy/config/local-config.json
  packages/solid-crs-id-proxy/config/proxy-config.json
  packages/solid-crs-id-proxy/package.json
  packages/solid-crs-webid/.dockerignore
  packages/solid-crs-webid/.gitignore
  packages/solid-crs-webid/Dockerfile
  packages/solid-crs-webid/config/file.json
  packages/solid-crs-webid/data/development/.acl
  packages/solid-crs-webid/data/development/.internal/setup/c2V0dXBDb21wbGV0ZWQtMi4w$.json
  packages/solid-crs-webid/data/development/.meta
  packages/solid-crs-webid/data/development/dgt-id-proxy/.acl
  packages/solid-crs-webid/data/development/dgt-id-proxy/.meta
  packages/solid-crs-webid/data/development/dgt-id-proxy/card$.ttl
  packages/solid-crs-webid/data/production/.acl
  packages/solid-crs-webid/data/production/.meta
  packages/solid-crs-webid/data/production/dgt-id-proxy/.acl
  packages/solid-crs-webid/data/production/dgt-id-proxy/.meta
  packages/solid-crs-webid/data/production/dgt-id-proxy/card$.ttl
  packages/solid-crs-webid/package-lock.json
  packages/solid-crs-webid/package.json
Labels: enhancement

#546 fix: correct proxy url for token signing
  packages/solid-crs-id-proxy/config/proxy-config.json
Labels: bug
