Repository netwerk-digitaal-erfgoed/solid-crs, pull requests merged in 2021-05, with the labels that each got.

#202 Search collections and objects
  packages/nde-erfgoed-components/lib/demo.ts
  packages/nde-erfgoed-components/lib/demo/demo-card.component.ts
  packages/nde-erfgoed-components/lib/demo/demo-sidebar-list.component.ts
  packages/nde-erfgoed-components/lib/forms/form-element.component.ts
  packages/nde-erfgoed-components/lib/index.ts
  packages/nde-erfgoed-components/lib/sidebar/sidebar-item-component.spec.ts
  packages/nde-erfgoed-components/lib/sidebar/sidebar-item.component.ts
  packages/nde-erfgoed-components/lib/sidebar/sidebar-list.component.ts
  packages/nde-erfgoed-components/package.json
  packages/nde-erfgoed-components/tests/setup.ts
  packages/nde-erfgoed-core/lib/collections/collection-memory-store.spec.ts
  packages/nde-erfgoed-core/lib/collections/collection-memory-store.ts
  packages/nde-erfgoed-core/lib/collections/collection-object-memory-store.spec.ts
  packages/nde-erfgoed-core/lib/collections/collection-object-memory-store.ts
  packages/nde-erfgoed-core/lib/collections/collection-object-store.ts
  packages/nde-erfgoed-core/lib/collections/collection-store.ts
  packages/nde-erfgoed-core/lib/index.ts
  packages/nde-erfgoed-core/lib/stores/memory-store.spec.ts
  packages/nde-erfgoed-core/lib/stores/memory-store.ts
  packages/nde-erfgoed-core/lib/stores/store.ts
  packages/nde-erfgoed-core/lib/utils/debounce.ts
  packages/nde-erfgoed-core/lib/utils/fulltext-match.ts
  packages/nde-erfgoed-core/package.json
  packages/nde-erfgoed-manage/lib/app-root.component.ts
  packages/nde-erfgoed-manage/lib/app.events.ts
  packages/nde-erfgoed-manage/lib/app.machine.ts
  packages/nde-erfgoed-manage/lib/app.ts
  packages/nde-erfgoed-manage/lib/common/solid/collection-object-solid-store.spec.ts
  packages/nde-erfgoed-manage/lib/common/solid/collection-object-solid-store.ts
  packages/nde-erfgoed-manage/lib/common/solid/collection-solid-store.spec.ts
  packages/nde-erfgoed-manage/lib/common/solid/collection-solid-store.ts
  packages/nde-erfgoed-manage/lib/common/solid/solid-store.spec.ts
  packages/nde-erfgoed-manage/lib/common/solid/solid-store.ts
  packages/nde-erfgoed-manage/lib/features/collection/collection-root.component.ts
  packages/nde-erfgoed-manage/lib/features/collection/collection.machine.ts
  packages/nde-erfgoed-manage/lib/features/search/search-root.component.spec.ts
  packages/nde-erfgoed-manage/lib/features/search/search-root.component.ts
  packages/nde-erfgoed-manage/lib/features/search/search.events.ts
  packages/nde-erfgoed-manage/lib/features/search/search.machine.spec.ts
  packages/nde-erfgoed-manage/lib/features/search/search.machine.ts
  packages/nde-erfgoed-manage/lib/i8n/nl-NL.json
  packages/nde-erfgoed-manage/lib/index.ts
  packages/nde-erfgoed-manage/package-lock.json
  packages/nde-erfgoed-manage/package.json
  packages/nde-erfgoed-manage/tests/setup.ts
  packages/nde-erfgoed-theme/lib/elements/grids.css
  packages/nde-erfgoed-theme/lib/theme.css
Labels: enhancement, feature

#220 Collection object feature specs
  specifications/assets/objects/object-details.svg
  specifications/pages/technical/create-object-root-page.adoc
  specifications/pages/technical/set-up-collection-object-feature.adoc
  specifications/pages/technical/update-collection-object-model.adoc
Labels: documentation

#243 Feat/create nde large card
  packages/solid-crs-components/lib/collections/large-card.component.spec.ts
  packages/solid-crs-components/lib/collections/large-card.component.ts
  packages/solid-crs-components/lib/demo.ts
  packages/solid-crs-components/lib/demo/demo-large-card.component.ts
  packages/solid-crs-components/lib/index.html
  packages/solid-crs-components/lib/index.ts
  packages/solid-crs-components/package.json
  packages/solid-crs-components/tests/setup.ts
Labels: enhancement
